// <auto-generated />

using System;
using System.Xml.Serialization;

namespace ARK.Model.XML
{
    public class XMLBoats
    {
        /// <remarks/>
        [XmlType(AnonymousType = true)]
        [XmlRoot(Namespace = "", IsNullable = false)]
        public partial class dataroot
        {
            private DateTime generatedField;

            /// <remarks/>
            [XmlElement("BådeSpecifik")]
            public datarootBådeSpecifik[] BådeSpecifik { get; set; }

            /// <remarks/>
            [XmlAttribute()]
            public DateTime generated
            {
                get
                {
                    return generatedField;
                }

                set
                {
                    generatedField = value;
                }
            }
        }

        /// <remarks/>
        [XmlType(AnonymousType = true)]
        public partial class datarootBådeSpecifik
        {
            /// <remarks/>
            public byte Aktiv { get; set; }

            /// <remarks/>
            public byte AntalPladser { get; set; }

            /// <remarks/>
            public byte BådType { get; set; }

            /// <remarks/>
            public byte ID { get; set; }

            /// <remarks/>
            public byte LangtursBåd { get; set; }

            /// <remarks/>
            public string Navn { get; set; }

            /// <remarks/>
            public byte Roforbud { get; set; }

            /// <remarks/>
            public byte SpecifikBådType { get; set; }
        }
    }
}