// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ARK.Model.XML
{
    public class XMLSunset
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class sun
        {
            #region Fields

            private sunDate dateField;

            private sunEvening eveningField;

            private sunLocation locationField;

            private sunMorning morningField;

            private decimal versionField;

            #endregion

            #region Public Properties

            /// <remarks/>
            public sunDate date
            {
                get
                {
                    return this.dateField;
                }

                set
                {
                    this.dateField = value;
                }
            }

            /// <remarks/>
            public sunEvening evening
            {
                get
                {
                    return this.eveningField;
                }

                set
                {
                    this.eveningField = value;
                }
            }

            /// <remarks/>
            public sunLocation location
            {
                get
                {
                    return this.locationField;
                }

                set
                {
                    this.locationField = value;
                }
            }

            /// <remarks/>
            public sunMorning morning
            {
                get
                {
                    return this.morningField;
                }

                set
                {
                    this.morningField = value;
                }
            }

            /// <remarks/>
            public decimal version
            {
                get
                {
                    return this.versionField;
                }

                set
                {
                    this.versionField = value;
                }
            }

            #endregion
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunDate
        {
            #region Fields

            private byte dayField;

            private byte dstField;

            private byte monthField;

            private byte timezoneField;

            #endregion

            #region Public Properties

            /// <remarks/>
            public byte day
            {
                get
                {
                    return this.dayField;
                }

                set
                {
                    this.dayField = value;
                }
            }

            /// <remarks/>
            public byte dst
            {
                get
                {
                    return this.dstField;
                }

                set
                {
                    this.dstField = value;
                }
            }

            /// <remarks/>
            public byte month
            {
                get
                {
                    return this.monthField;
                }

                set
                {
                    this.monthField = value;
                }
            }

            /// <remarks/>
            public byte timezone
            {
                get
                {
                    return this.timezoneField;
                }

                set
                {
                    this.timezoneField = value;
                }
            }

            #endregion
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunEvening
        {
            #region Fields

            private string sunsetField;

            private sunEveningTwilight twilightField;

            #endregion

            #region Public Properties

            /// <remarks/>
            public string sunset
            {
                get
                {
                    return this.sunsetField;
                }

                set
                {
                    this.sunsetField = value;
                }
            }

            /// <remarks/>
            public sunEveningTwilight twilight
            {
                get
                {
                    return this.twilightField;
                }

                set
                {
                    this.twilightField = value;
                }
            }

            #endregion
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunEveningTwilight
        {
            #region Fields

            private string astronomicalField;

            private string civilField;

            private string nauticalField;

            #endregion

            #region Public Properties

            /// <remarks/>
            public string astronomical
            {
                get
                {
                    return this.astronomicalField;
                }

                set
                {
                    this.astronomicalField = value;
                }
            }

            /// <remarks/>
            public string civil
            {
                get
                {
                    return this.civilField;
                }

                set
                {
                    this.civilField = value;
                }
            }

            /// <remarks/>
            public string nautical
            {
                get
                {
                    return this.nauticalField;
                }

                set
                {
                    this.nauticalField = value;
                }
            }

            #endregion
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunLocation
        {
            #region Fields

            private decimal latitudeField;

            private decimal longitudeField;

            #endregion

            #region Public Properties

            /// <remarks/>
            public decimal latitude
            {
                get
                {
                    return this.latitudeField;
                }

                set
                {
                    this.latitudeField = value;
                }
            }

            /// <remarks/>
            public decimal longitude
            {
                get
                {
                    return this.longitudeField;
                }

                set
                {
                    this.longitudeField = value;
                }
            }

            #endregion
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunMorning
        {
            #region Fields

            private string sunriseField;

            private sunMorningTwilight twilightField;

            #endregion

            #region Public Properties

            /// <remarks/>
            public string sunrise
            {
                get
                {
                    return this.sunriseField;
                }

                set
                {
                    this.sunriseField = value;
                }
            }

            /// <remarks/>
            public sunMorningTwilight twilight
            {
                get
                {
                    return this.twilightField;
                }

                set
                {
                    this.twilightField = value;
                }
            }

            #endregion
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunMorningTwilight
        {
            #region Fields

            private string astronomicalField;

            private string civilField;

            private string nauticalField;

            #endregion

            #region Public Properties

            /// <remarks/>
            public string astronomical
            {
                get
                {
                    return this.astronomicalField;
                }

                set
                {
                    this.astronomicalField = value;
                }
            }

            /// <remarks/>
            public string civil
            {
                get
                {
                    return this.civilField;
                }

                set
                {
                    this.civilField = value;
                }
            }

            /// <remarks/>
            public string nautical
            {
                get
                {
                    return this.nauticalField;
                }

                set
                {
                    this.nauticalField = value;
                }
            }

            #endregion
        }
    }
}