// <auto-generated />
namespace ARK.Model.XML
{
    public class XMLSunset
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class sun
        {
            private sunDate dateField;

            private sunEvening eveningField;

            private sunLocation locationField;

            private sunMorning morningField;

            private decimal versionField;

            /// <remarks/>
            public sunDate date
            {
                get
                {
                    return dateField;
                }

                set
                {
                    dateField = value;
                }
            }

            /// <remarks/>
            public sunEvening evening
            {
                get
                {
                    return eveningField;
                }

                set
                {
                    eveningField = value;
                }
            }

            /// <remarks/>
            public sunLocation location
            {
                get
                {
                    return locationField;
                }

                set
                {
                    locationField = value;
                }
            }

            /// <remarks/>
            public sunMorning morning
            {
                get
                {
                    return morningField;
                }

                set
                {
                    morningField = value;
                }
            }

            /// <remarks/>
            public decimal version
            {
                get
                {
                    return versionField;
                }

                set
                {
                    versionField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunDate
        {
            private byte dayField;

            private byte dstField;

            private byte monthField;

            private byte timezoneField;

            /// <remarks/>
            public byte day
            {
                get
                {
                    return dayField;
                }

                set
                {
                    dayField = value;
                }
            }

            /// <remarks/>
            public byte dst
            {
                get
                {
                    return dstField;
                }

                set
                {
                    dstField = value;
                }
            }

            /// <remarks/>
            public byte month
            {
                get
                {
                    return monthField;
                }

                set
                {
                    monthField = value;
                }
            }

            /// <remarks/>
            public byte timezone
            {
                get
                {
                    return timezoneField;
                }

                set
                {
                    timezoneField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunEvening
        {
            private string sunsetField;

            private sunEveningTwilight twilightField;

            /// <remarks/>
            public string sunset
            {
                get
                {
                    return sunsetField;
                }

                set
                {
                    sunsetField = value;
                }
            }

            /// <remarks/>
            public sunEveningTwilight twilight
            {
                get
                {
                    return twilightField;
                }

                set
                {
                    twilightField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunEveningTwilight
        {
            private string astronomicalField;

            private string civilField;

            private string nauticalField;

            /// <remarks/>
            public string astronomical
            {
                get
                {
                    return astronomicalField;
                }

                set
                {
                    astronomicalField = value;
                }
            }

            /// <remarks/>
            public string civil
            {
                get
                {
                    return civilField;
                }

                set
                {
                    civilField = value;
                }
            }

            /// <remarks/>
            public string nautical
            {
                get
                {
                    return nauticalField;
                }

                set
                {
                    nauticalField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunLocation
        {
            private decimal latitudeField;

            private decimal longitudeField;

            /// <remarks/>
            public decimal latitude
            {
                get
                {
                    return latitudeField;
                }

                set
                {
                    latitudeField = value;
                }
            }

            /// <remarks/>
            public decimal longitude
            {
                get
                {
                    return longitudeField;
                }

                set
                {
                    longitudeField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunMorning
        {
            private string sunriseField;

            private sunMorningTwilight twilightField;

            /// <remarks/>
            public string sunrise
            {
                get
                {
                    return sunriseField;
                }

                set
                {
                    sunriseField = value;
                }
            }

            /// <remarks/>
            public sunMorningTwilight twilight
            {
                get
                {
                    return twilightField;
                }

                set
                {
                    twilightField = value;
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class sunMorningTwilight
        {
            private string astronomicalField;

            private string civilField;

            private string nauticalField;

            /// <remarks/>
            public string astronomical
            {
                get
                {
                    return astronomicalField;
                }

                set
                {
                    astronomicalField = value;
                }
            }

            /// <remarks/>
            public string civil
            {
                get
                {
                    return civilField;
                }

                set
                {
                    civilField = value;
                }
            }

            /// <remarks/>
            public string nautical
            {
                get
                {
                    return nauticalField;
                }

                set
                {
                    nauticalField = value;
                }
            }
        }
    }
}