//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public int Member_Id { get; set; }
        public bool ContactTrip { get; set; }
        public bool ContactDark { get; set; }
    
        public virtual Members Members { get; set; }
    }
}
