//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boats
    {
        public Boats()
        {
            this.DamageForms = new HashSet<DamageForms>();
            this.LongTripForms = new HashSet<LongTripForms>();
            this.Trips = new HashSet<Trips>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int NumberofSeats { get; set; }
        public bool Active { get; set; }
        public int SpecificBoatType { get; set; }
        public bool LongTripBoat { get; set; }
        public bool HaveCox { get; set; }
        public int NewPrice { get; set; }
        public int Year { get; set; }
        public string InformationString { get; set; }
    
        public virtual ICollection<DamageForms> DamageForms { get; set; }
        public virtual ICollection<LongTripForms> LongTripForms { get; set; }
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
