//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageForms
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public bool Functional { get; set; }
        public bool Closed { get; set; }
        public int RegisteringMemberId { get; set; }
        public int BoatId { get; set; }
    
        public virtual Boats Boats { get; set; }
        public virtual Members Members { get; set; }
    }
}
