//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetSMS
    {
        public int Id { get; set; }
        public string From { get; set; }
        public string Text { get; set; }
        public System.DateTime RecievedDate { get; set; }
        public bool Handled { get; set; }
    }
}
