//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class LongTripForms
    {
        public LongTripForms()
        {
            this.Members1 = new HashSet<Members>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BoatId { get; set; }
        public int Status { get; set; }
        public System.DateTime FormCreated { get; set; }
        public System.DateTime PlannedStartDate { get; set; }
        public System.DateTime PlannedEndDate { get; set; }
        public string TourDescription { get; set; }
        public string DistancesPerDay { get; set; }
        public string CampSites { get; set; }
        public int ResponsibleMemberId { get; set; }
    
        public virtual Boats Boats { get; set; }
        public virtual Members Members { get; set; }
        public virtual ICollection<Members> Members1 { get; set; }
    }
}
