//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public Members()
        {
            this.Admins = new HashSet<Admins>();
            this.DamageForms = new HashSet<DamageForms>();
            this.LongTripForms = new HashSet<LongTripForms>();
            this.LongTripForms1 = new HashSet<LongTripForms>();
            this.Trips = new HashSet<Trips>();
        }
    
        public int Id { get; set; }
        public bool Active { get; set; }
        public int MemberNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public int ZipCode { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string PhoneWork { get; set; }
        public string Cellphone { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool Released { get; set; }
        public bool SwimmingTest { get; set; }
        public bool ShortTripCox { get; set; }
        public bool LongTripCox { get; set; }
        public bool MayUseSculler { get; set; }
        public bool MayUseOutrigger { get; set; }
        public bool MayUseKayak { get; set; }
    
        public virtual ICollection<Admins> Admins { get; set; }
        public virtual ICollection<DamageForms> DamageForms { get; set; }
        public virtual ICollection<LongTripForms> LongTripForms { get; set; }
        public virtual ICollection<LongTripForms> LongTripForms1 { get; set; }
        public virtual ICollection<Trips> Trips { get; set; }
    }
}
