//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Boats> Boats { get; set; }
        public virtual DbSet<DamageForms> DamageForms { get; set; }
        public virtual DbSet<DamageTypes> DamageTypes { get; set; }
        public virtual DbSet<FTPInfoes> FTPInfoes { get; set; }
        public virtual DbSet<GetSMS> GetSMS { get; set; }
        public virtual DbSet<LongTripForms> LongTripForms { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Seasons> Seasons { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<SMS> SMS { get; set; }
        public virtual DbSet<StandardTrips> StandardTrips { get; set; }
        public virtual DbSet<Trips> Trips { get; set; }
        public virtual DbSet<TripWarningSms> TripWarningSms { get; set; }
    }
}
