//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seasons
    {
        public int Id { get; set; }
        public System.DateTime SeasonStart { get; set; }
        public System.DateTime SeasonEnd { get; set; }
    }
}
