//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS
    {
        public string Reciever { get; set; }
        public string Name { get; set; }
        public bool Dispatched { get; set; }
        public string Message { get; set; }
        public bool approved { get; set; }
        public System.DateTime Time { get; set; }
        public bool Handled { get; set; }
    }
}
