//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARK.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripWarningSms
    {
        public Nullable<System.DateTime> SentSms { get; set; }
        public Nullable<System.DateTime> RecievedSms { get; set; }
        public Nullable<System.DateTime> SentAdminSms { get; set; }
        public int Id { get; set; }
    
        public virtual Trips Trips { get; set; }
    }
}
