// <auto-generated />

using System.Data.Entity.Migrations;

using ARK.Model.DB;

using MySql.Data.Entity;

namespace ARK.Migrations
{
    internal sealed class Configuration : DbMigrationsConfiguration<DbArkContext>
    {
        #region Constructors and Destructors

        public Configuration()
        {
            this.AutomaticMigrationsEnabled = true;
            this.SetSqlGenerator("MySql.Data.MySqlClient", new MySqlMigrationSqlGenerator());
        }

        #endregion

        #region Methods

        protected override void Seed(DbArkContext context)
        {
            // This method will be called after migrating to the latest version.

            // You can use the DbSet<T>.AddOrUpdate() helper extension method 
            // to avoid creating duplicate seed data. E.g.
            // context.People.AddOrUpdate(
            // p => p.FullName,
            // new Person { FullName = "Andrew Peters" },
            // new Person { FullName = "Brice Lambson" },
            // new Person { FullName = "Rowan Miller" }
            // );
        }

        #endregion
    }
}